export const FONT_CATEGORIES = [
  {
    name: 'Sans-Serif',
    fonts: [
      { value: 'Inter, sans-serif', label: 'Inter' },
      { value: 'Roboto, sans-serif', label: 'Roboto' },
      { value: 'Open Sans, sans-serif', label: 'Open Sans' },
      { value: 'Montserrat, sans-serif', label: 'Montserrat' },
      { value: 'Lato, sans-serif', label: 'Lato' },
      { value: 'Poppins, sans-serif', label: 'Poppins' },
      { value: 'Raleway, sans-serif', label: 'Raleway' },
      { value: 'Nunito, sans-serif', label: 'Nunito' },
      { value: 'Work Sans, sans-serif', label: 'Work Sans' },
      { value: 'DM Sans, sans-serif', label: 'DM Sans' },
      { value: '"Plus Jakarta Sans", sans-serif', label: 'Plus Jakarta Sans' },
      { value: 'Manrope, sans-serif', label: 'Manrope' },
      { value: 'Figtree, sans-serif', label: 'Figtree' },
      { value: 'Outfit, sans-serif', label: 'Outfit' },
      { value: 'Sora, sans-serif', label: 'Sora' },
      { value: 'Lexend, sans-serif', label: 'Lexend' },
      { value: 'Rubik, sans-serif', label: 'Rubik' },
      { value: 'Urbanist, sans-serif', label: 'Urbanist' },
      { value: 'Jost, sans-serif', label: 'Jost' },
      { value: 'Barlow, sans-serif', label: 'Barlow' },
      { value: 'Oswald, sans-serif', label: 'Oswald' },
      { value: 'Archivo, sans-serif', label: 'Archivo' },
      { value: 'Overpass, sans-serif', label: 'Overpass' },
      { value: 'Arial, sans-serif', label: 'Arial' },
    ],
  },
  {
    name: 'Serif',
    fonts: [
      { value: 'Merriweather, serif', label: 'Merriweather' },
      { value: '"Playfair Display", serif', label: 'Playfair Display' },
      { value: 'Lora, serif', label: 'Lora' },
      { value: '"EB Garamond", serif', label: 'EB Garamond' },
      { value: '"Cormorant Garamond", serif', label: 'Cormorant Garamond' },
      { value: '"Bodoni Moda", serif', label: 'Bodoni Moda' },
      { value: '"DM Serif Display", serif', label: 'DM Serif Display' },
      { value: '"DM Serif Text", serif', label: 'DM Serif Text' },
      { value: 'Spectral, serif', label: 'Spectral' },
      { value: 'Fraunces, serif', label: 'Fraunces' },
      { value: '"Libre Baskerville", serif', label: 'Libre Baskerville' },
      { value: '"PT Serif", serif', label: 'PT Serif' },
      { value: 'Cinzel, serif', label: 'Cinzel' },
      { value: '"Times New Roman", serif', label: 'Times New Roman' },
      { value: 'Georgia, serif', label: 'Georgia' },
    ],
  },
  {
    name: 'Display',
    fonts: [
      { value: '"Bebas Neue", sans-serif', label: 'Bebas Neue' },
      { value: 'Anton, sans-serif', label: 'Anton' },
      { value: '"Abril Fatface", serif', label: 'Abril Fatface' },
      { value: '"Cinzel Decorative", serif', label: 'Cinzel Decorative' },
      { value: 'Righteous, sans-serif', label: 'Righteous' },
      { value: '"Sigmar", sans-serif', label: 'Sigmar' },
      { value: '"Luckiest Guy", sans-serif', label: 'Luckiest Guy' },
      { value: '"Press Start 2P", cursive', label: 'Press Start 2P' },
      { value: 'Audiowide, sans-serif', label: 'Audiowide' },
      { value: 'Orbitron, sans-serif', label: 'Orbitron' },
      { value: 'Impact, sans-serif', label: 'Impact' },
    ],
  },
  {
    name: 'Handwriting',
    fonts: [
      { value: 'Pacifico, cursive', label: 'Pacifico' },
      { value: 'Caveat, cursive', label: 'Caveat' },
      { value: 'Satisfy, cursive', label: 'Satisfy' },
      { value: '"Dancing Script", cursive', label: 'Dancing Script' },
      { value: '"Patrick Hand", cursive', label: 'Patrick Hand' },
      { value: 'Kalam, cursive', label: 'Kalam' },
      { value: '"Indie Flower", cursive', label: 'Indie Flower' },
      { value: '"Permanent Marker", cursive', label: 'Permanent Marker' },
    ],
  },
  {
    name: 'Monospace',
    fonts: [
      { value: '"Courier Prime", monospace', label: 'Courier Prime' },
      { value: '"Fira Code", monospace', label: 'Fira Code' },
      { value: '"JetBrains Mono", monospace', label: 'JetBrains Mono' },
      { value: '"Source Code Pro", monospace', label: 'Source Code Pro' },
      { value: '"Space Mono", monospace', label: 'Space Mono' },
      { value: '"IBM Plex Mono", monospace', label: 'IBM Plex Mono' },
      { value: '"DM Mono", monospace', label: 'DM Mono' },
      { value: '"Courier New", monospace', label: 'Courier New' },
    ],
  },
]

export const ALL_FONTS = FONT_CATEGORIES.flatMap(c => c.fonts)
export const FONT_FAMILIES = ALL_FONTS.map(f => f.value)

export const GOOGLE_FONTS_URL = (
  'https://fonts.googleapis.com/css2?' +
  [
    'family=Inter:wght@400;700',
    'family=Roboto:wght@400;700',
    'family=Open+Sans:wght@400;700',
    'family=Montserrat:wght@400;700',
    'family=Lato:wght@400;700',
    'family=Poppins:wght@400;700',
    'family=Raleway:wght@400;700',
    'family=Nunito:wght@400;700',
    'family=Work+Sans:wght@400;700',
    'family=DM+Sans:wght@400;700',
    'family=Plus+Jakarta+Sans:wght@400;700',
    'family=Manrope:wght@400;700',
    'family=Figtree:wght@400;700',
    'family=Outfit:wght@400;700',
    'family=Sora:wght@400;700',
    'family=Lexend:wght@400;700',
    'family=Rubik:wght@400;700',
    'family=Urbanist:wght@400;700',
    'family=Jost:wght@400;700',
    'family=Barlow:wght@400;700',
    'family=Oswald:wght@400;700',
    'family=Archivo:wght@400;700',
    'family=Overpass:wght@400;700',
    'family=Merriweather:wght@400;700',
    'family=Playfair+Display:wght@400;700',
    'family=Lora:wght@400;700',
    'family=EB+Garamond:wght@400;700',
    'family=Cormorant+Garamond:wght@400;700',
    'family=Bodoni+Moda:wght@400;700',
    'family=DM+Serif+Display',
    'family=DM+Serif+Text',
    'family=Spectral:wght@400;700',
    'family=Fraunces:wght@400;700',
    'family=Libre+Baskerville:wght@400;700',
    'family=PT+Serif:wght@400;700',
    'family=Cinzel:wght@400;700',
    'family=Bebas+Neue',
    'family=Anton',
    'family=Abril+Fatface',
    'family=Cinzel+Decorative:wght@400;700',
    'family=Righteous',
    'family=Sigmar',
    'family=Luckiest+Guy',
    'family=Press+Start+2P',
    'family=Audiowide',
    'family=Orbitron:wght@400;700',
    'family=Pacifico',
    'family=Caveat:wght@400;700',
    'family=Satisfy',
    'family=Dancing+Script:wght@400;700',
    'family=Patrick+Hand',
    'family=Kalam:wght@400;700',
    'family=Indie+Flower',
    'family=Permanent+Marker',
    'family=Courier+Prime',
    'family=Fira+Code:wght@400;700',
    'family=JetBrains+Mono:wght@400;700',
    'family=Source+Code+Pro:wght@400;700',
    'family=Space+Mono:wght@400;700',
    'family=IBM+Plex+Mono:wght@400;700',
    'family=DM+Mono:wght@400;700',
  ].join('&') +
  '&display=swap'
)
